/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#c7c4d8",
        "on-primary-container": "#1b0091",
        "tertiary-container": "#db761f",
        "surface": "#051424",
        "on-primary-fixed": "#100069",
        "primary-fixed": "#e3dfff",
        "on-error": "#690005",
        "on-tertiary-container": "#461f00",
        "inverse-surface": "#d4e4fa",
        "tertiary": "#ffb785",
        "on-primary": "#2000a4",
        "surface-container-highest": "#273647",
        "on-secondary": "#1c00a6",
        "surface-container-lowest": "#010f1f",
        "on-secondary-container": "#b3b1ff",
        "surface-dim": "#051424",
        "tertiary-fixed": "#ffdcc6",
        "tertiary-fixed-dim": "#ffb785",
        "inverse-on-surface": "#233143",
        "on-tertiary-fixed": "#301400",
        "on-tertiary": "#502500",
        "surface-tint": "#c4c0ff",
        "primary-container": "#8781ff",
        "surface-bright": "#2c3a4c",
        "on-error-container": "#ffdad6",
        "outline-variant": "#464555",
        "primary": "#c4c0ff",
        "surface-container": "#122131",
        "on-tertiary-fixed-variant": "#713700",
        "primary-fixed-dim": "#c4c0ff",
        "on-primary-fixed-variant": "#3622ca",
        "error-container": "#93000a",
        "secondary": "#c3c0ff",
        "error": "#ffb4ab",
        "on-secondary-fixed-variant": "#3529c2",
        "secondary-container": "#372cc5",
        "on-background": "#d4e4fa",
        "secondary-fixed-dim": "#c3c0ff",
        "outline": "#918fa1",
        "secondary-fixed": "#e2dfff",
        "on-surface": "#d4e4fa",
        "on-secondary-fixed": "#0e006a",
        "surface-variant": "#273647",
        "inverse-primary": "#4f44e2",
        "background": "#051424",
        "surface-container-high": "#1c2b3c",
        "surface-container-low": "#0d1c2d"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "base": "4px",
        "xs": "8px",
        "sm": "16px",
        "md": "24px",
        "lg": "32px",
        "xl": "48px",
        "container-margin": "24px",
        "gutter": "20px"
      },
      fontFamily: {
        "h1": ["Inter", "sans-serif"],
        "h2": ["Inter", "sans-serif"],
        "h3": ["Inter", "sans-serif"],
        "subtitle": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "h1": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "h2": ["32px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "h3": ["24px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "subtitle": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
